name: synji_calendar
description: "A professional calendar application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  intl: ^0.20.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  logger: ^2.0.2
  sqflite: ^2.3.0
  path: ^1.9.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.2
  cookie_jar: ^4.0.8
  flutter_slidable: ^3.0.1
  receive_sharing_intent: ^1.6.1
  lpinyin: ^2.0.3
  connectivity_plus: ^6.1.1
  device_calendar: ^4.3.2 # 访问系统日历
  permission_handler: ^11.3.1 # 权限管理
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#0081E0"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
